server:
  port: 8080

spring:
  application:
    name: InsuranceApp-SpringBoot

  profiles:
    # IntelliJ の実行構成で切り替える想定
    # 例：環境変数 SPRING_PROFILES_ACTIVE=production / stub
    group:
      production: production
      stub: stub

# ── Actuator の設定 ──
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
